### ISSUE TITLE
Run python in_domain_run.py, report errors: NotImplementedError

### ISSUE THREAD

**Issue by Luckypolo2** [Zhang-xie/WiGr#2]
ENV: pytorch1.8 pytorch lightning1.2.8 python3.8
```python in_domain_run.py``` this command can't work
```shell
/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py:68: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 96 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)
Validation sanity check:   0%|                                                                                                                                                                  | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "in_domain_run.py", line 260, in <module>
    run(args,setting)
  File "in_domain_run.py", line 103, in run
    trainer.fit(model,tr_loader,te_loader)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 607, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in run_sanity_check
    _, eval_results = self.run_evaluation(max_batches=self.num_sanity_val_batches)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 713, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 330, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 33, in __getitem__
    raise NotImplementedError
NotImplementedError
```

**Comment by Aom-sushar** [comment]
> ENV：pytorch1.8 pytorch lightning1.2.8 python3.8 `python in_domain_run.py`这个命令不起作用>> ```外壳> /root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py:68：用户警告：数据加载器，val dataloader 0，没有多少工人，这可能是瓶颈。考虑在“DataLoader”init中增加“num_workers”参数的值（尝试96，这是这台机器上的cpus数），以提高性能。> warnings.warn（*args，**kwargs）>验证理智检查：0%|| 0/1 [00:00<?, ?it/s]回溯（最近最后一次通话）：>文件“in_domain_run.py”，第260行，在<module>中>运行（args，设置）>文件“in_domain_run.py”，第103行，运行中> trainer.fit（模型，tr_loader，te_loader）>文件“/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py”，第499行，适合> self.dispatch（）>文件“/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py”，第546行，在调度中> self.accelerator.start_training（self）>文件“/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py”，第73行，在start_training中> self.training_type_plugin.start_training（培训师）>文件“/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py”，第114行，在start_training中> self._results = trainer.run_train()>文件“/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py”，第607行，在run_train中> self.run_sanity_check（self.lightning_module）>文件“/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py”，第864行，在run_sanity_check中> _, eval_results = self.run_evaluation(max_batches=self.num_sanity_val_batches)>文件“/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py”，第713行，在run_evaluation中>对于batch_idx，批量在枚举（数据加载器）：>文件“/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py”，第517行，在__next__> 数据 = self._next_data()>文件“/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py”，第557行，在_next_data中> data = self._dataset_fetcher.fetch(index) # may raise StopIteration>文件“/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py”，第44行，在fetch中> data = [self.dataset[idx] for idx in possibly_batched_index]>文件“/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py”，第44行，在<listcomp>> data = [self.dataset[idx] for idx in possibly_batched_index]>文件“/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataset.py”，第330行，在__getitem__>返回self.dataset[self.indices[idx]]>文件“/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataset.py”，第33行，在__getitem__> raise NotImplementedError> NotImplementedError> ``
你好,我也遇到了这个问题,请问您解决了吗?

**Comment by Aom-sushar** [comment]
> ENV: pytorch1.8 pytorch lightning1.2.8 python3.8 `python in_domain_run.py` this command can't work
> 
> ```shell
> /root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py:68: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 96 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
>   warnings.warn(*args, **kwargs)
> Validation sanity check:   0%|                                                                                                                                                                  | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
>   File "in_domain_run.py", line 260, in <module>
>     run(args,setting)
>   File "in_domain_run.py", line 103, in run
>     trainer.fit(model,tr_loader,te_loader)
>   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
>     self.dispatch()
>   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
>     self.accelerator.start_training(self)
>   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
>     self.training_type_plugin.start_training(trainer)
>   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
>     self._results = trainer.run_train()
>   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 607, in run_train
>     self.run_sanity_check(self.lightning_module)
>   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in run_sanity_check
>     _, eval_results = self.run_evaluation(max_batches=self.num_sanity_val_batches)
>   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 713, in run_evaluation
>     for batch_idx, batch in enumerate(dataloader):
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
>     data = self._next_data()
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
>     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 330, in __getitem__
>     return self.dataset[self.indices[idx]]
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 33, in __getitem__
>     raise NotImplementedError
> NotImplementedError
> ```

你好我也遇到了这个问题,请问您解决了吗?

**Comment by Xloading-919** [comment]
> > ENV: pytorch1.8 pytorch lightning1.2.8 python3.8 `python in_domain_run.py` this command can't work
> > ```shell
> > /root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py:68: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 96 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
> >   warnings.warn(*args, **kwargs)
> > Validation sanity check:   0%|                                                                                                                                                                  | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
> >   File "in_domain_run.py", line 260, in <module>
> >     run(args,setting)
> >   File "in_domain_run.py", line 103, in run
> >     trainer.fit(model,tr_loader,te_loader)
> >   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
> >     self.dispatch()
> >   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
> >     self.accelerator.start_training(self)
> >   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
> >     self.training_type_plugin.start_training(trainer)
> >   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
> >     self._results = trainer.run_train()
> >   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 607, in run_train
> >     self.run_sanity_check(self.lightning_module)
> >   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in run_sanity_check
> >     _, eval_results = self.run_evaluation(max_batches=self.num_sanity_val_batches)
> >   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 713, in run_evaluation
> >     for batch_idx, batch in enumerate(dataloader):
> >   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
> >     data = self._next_data()
> >   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
> >     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
> >   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> >     data = [self.dataset[idx] for idx in possibly_batched_index]
> >   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
> >     data = [self.dataset[idx] for idx in possibly_batched_index]
> >   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 330, in __getitem__
> >     return self.dataset[self.indices[idx]]
> >   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 33, in __getitem__
> >     raise NotImplementedError
> > NotImplementedError
> > ```
> 
> 你好我也遇到了这个问题,请问您解决了吗?

你好，我也是这样，你解决了吗

**Comment by onlynewbie** [comment]
> > > ENV: pytorch1.8 pytorch lightning1.2.8 python3.8 `python in_domain_run.py` this command can't work
> > > ```shell
> > > /root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py:68: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 96 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
> > >   warnings.warn(*args, **kwargs)
> > > Validation sanity check:   0%|                                                                                                                                                                  | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
> > >   File "in_domain_run.py", line 260, in <module>
> > >     run(args,setting)
> > >   File "in_domain_run.py", line 103, in run
> > >     trainer.fit(model,tr_loader,te_loader)
> > >   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
> > >     self.dispatch()
> > >   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
> > >     self.accelerator.start_training(self)
> > >   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
> > >     self.training_type_plugin.start_training(trainer)
> > >   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
> > >     self._results = trainer.run_train()
> > >   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 607, in run_train
> > >     self.run_sanity_check(self.lightning_module)
> > >   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in run_sanity_check
> > >     _, eval_results = self.run_evaluation(max_batches=self.num_sanity_val_batches)
> > >   File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 713, in run_evaluation
> > >     for batch_idx, batch in enumerate(dataloader):
> > >   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
> > >     data = self._next_data()
> > >   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
> > >     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
> > >   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> > >     data = [self.dataset[idx] for idx in possibly_batched_index]
> > >   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
> > >     data = [self.dataset[idx] for idx in possibly_batched_index]
> > >   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 330, in __getitem__
> > >     return self.dataset[self.indices[idx]]
> > >   File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 33, in __getitem__
> > >     raise NotImplementedError
> > > NotImplementedError
> > > ```
> > 
> > 
> > 你好我也遇到了这个问题,请问您解决了吗?
> 
> 你好，我也是这样，你解决了吗

你好，为什么我没找到datatrain_activity_label.npy这个文件，您在哪找到的

**Comment by Xloading-919** [comment]
> 你好，为什么我没找到datatrain_activity_label.npy这个文件，您在哪找到的
这个是ARIL数据集里的文件吧，这个项目的代码里不包含数据集的文件的，需要单独去下载数据集

**Comment by xUyONGzHI1234** [comment]
> > 你好，为什么我没找到datatrain_activity_label.npy这个文件，您在哪找到的
> > 这个是ARIL数据集里的文件吧，这个项目的代码里不包含数据集的文件的，需要单独去下载数据集

Hello, the downloaded ARIL data set has four files like the one in the first image. But the file path name required to load in the code is what the second image shows. Do you know how to solve it?
![1729841669270](https://github.com/user-attachments/assets/a433a8e3-a441-4e8b-9509-767ffb8f9c72)
![Uploading 1729841707917.png…]()
